# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CleanMediaInterface(object):
    def setupUi(self, CleanMediaInterface):
        CleanMediaInterface.setObjectName("CleanMediaInterface")
        CleanMediaInterface.resize(1024, 841)
        CleanMediaInterface.setMinimumSize(QtCore.QSize(1024, 768))
        CleanMediaInterface.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(CleanMediaInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 90, 981, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 6, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 8, 5, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LabelXML = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.LabelXML.setFont(font)
        self.LabelXML.setObjectName("LabelXML")
        self.horizontalLayout.addWidget(self.LabelXML)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 5, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ButtonInfo = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.ButtonInfo.setFont(font)
        self.ButtonInfo.setObjectName("ButtonInfo")
        self.horizontalLayout_2.addWidget(self.ButtonInfo)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        self.ButtonXML = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.ButtonXML.setFont(font)
        self.ButtonXML.setObjectName("ButtonXML")
        self.gridLayout.addWidget(self.ButtonXML, 1, 1, 1, 1)
        self.ButtonRom = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.ButtonRom.setFont(font)
        self.ButtonRom.setObjectName("ButtonRom")
        self.gridLayout.addWidget(self.ButtonRom, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.ButtonComenzar = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonComenzar.setFont(font)
        self.ButtonComenzar.setObjectName("ButtonComenzar")
        self.horizontalLayout_4.addWidget(self.ButtonComenzar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 3, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 8, 3, 1, 1)
        self.LabelROM = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.LabelROM.setFont(font)
        self.LabelROM.setObjectName("LabelROM")
        self.gridLayout.addWidget(self.LabelROM, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 7, 3, 1, 1)
        self.radioButtonBorrar = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.radioButtonBorrar.setFont(font)
        self.radioButtonBorrar.setObjectName("radioButtonBorrar")
        self.gridLayout.addWidget(self.radioButtonBorrar, 6, 5, 1, 1)
        self.radioButtonMover = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.radioButtonMover.setFont(font)
        self.radioButtonMover.setObjectName("radioButtonMover")
        self.gridLayout.addWidget(self.radioButtonMover, 7, 5, 1, 1)
        CleanMediaInterface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CleanMediaInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuSalir = QtWidgets.QMenu(self.menubar)
        self.menuSalir.setObjectName("menuSalir")
        CleanMediaInterface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CleanMediaInterface)
        self.statusbar.setObjectName("statusbar")
        CleanMediaInterface.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSalir.menuAction())

        self.retranslateUi(CleanMediaInterface)
        QtCore.QMetaObject.connectSlotsByName(CleanMediaInterface)
        CleanMediaInterface.setTabOrder(self.ButtonRom, self.ButtonXML)
        CleanMediaInterface.setTabOrder(self.ButtonXML, self.ButtonComenzar)

    def retranslateUi(self, CleanMediaInterface):
        _translate = QtCore.QCoreApplication.translate
        CleanMediaInterface.setWindowTitle(_translate("CleanMediaInterface", "Clean Media V.2"))
        self.LabelXML.setText(_translate("CleanMediaInterface", "Archivo . XML"))
        self.ButtonInfo.setText(_translate("CleanMediaInterface", "Info"))
        self.ButtonXML.setText(_translate("CleanMediaInterface", "Archivo .XML"))
        self.ButtonRom.setText(_translate("CleanMediaInterface", "Directorio Roms"))
        self.ButtonComenzar.setText(_translate("CleanMediaInterface", "Comenzar!!!"))
        self.LabelROM.setText(_translate("CleanMediaInterface", "Directorio Roms"))
        self.radioButtonBorrar.setText(_translate("CleanMediaInterface", "Borrar archivos no utilizados"))
        self.radioButtonMover.setText(_translate("CleanMediaInterface", "Mover archivos a carpeta BACKUP"))
        self.menuSalir.setTitle(_translate("CleanMediaInterface", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CleanMediaInterface = QtWidgets.QMainWindow()
    ui = Ui_CleanMediaInterface()
    ui.setupUi(CleanMediaInterface)
    CleanMediaInterface.show()
    sys.exit(app.exec_())

